apiVersion: apps/v1
kind: Deployment
metadata:
  name: educonnect
  labels:
    app: educonnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: educonnect
  template:
    metadata:
      labels:
        app: educonnect
    spec:
      containers:
      - name: educonnect
        image: educonnect:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: educonnect
spec:
  selector:
    app: educonnect
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer 